#!/bin/bash
docker-compose -f cvat/docker-compose.yml build cvat
if [ $DOCKER_REPO == "atcommons/cvat" ]
then
  exit 0
elif [ $DOCKER_REPO == "atcommons/cvat_ui" ]
then
  docker-compose -f cvat/docker-compose.yml build cvat_ui
else
  exit 0
fi
