#!/bin/bash
set -uex

# checking which repo is calling the build
if [ $DOCKER_REPO == "index.docker.io/atcommons/cvat" ]
then
  # calling the corresponding build
  docker-compose -f cvat/docker-compose.yml build cvat
  # renaming the images for docker hub to find it
  docker image tag cvat/server:latest ${IMAGE_NAME}
elif [ $DOCKER_REPO == "index.docker.io/atcommons/cvat_ui" ]
then
  docker-compose -f cvat/docker-compose.yml build cvat_ui
  docker image tag cvat_ui/server:latest ${IMAGE_NAME}
else
  echo "no matching repo name in build hooks"
  exit 1
fi