name: latest version

on:
  schedule:
    - cron: '20 1 * * *'

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get available tags
        run:  |
	      git ls-remote --tags https://github.com/openvinotoolkit/cvat.git | sed -n -e 's/^.*tags\///p' | sed -ne '/v[0-9].[0-9].[0-9]$/p' | tail -1 > latest_tag.txt
	    

      - name: Check remote version with local
        run: |
           grep -q $(cat VERSION) latest_tag.txt
